### ISSUE TITLE
ERROR: '<' not supported between instances of 'float' and 'str'

### ISSUE THREAD

**Issue by ssean** [TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection#87]
Can anyone help with this? I'm receiving the following error when the script starts downloading the video file. Thanks!

[download]   0.0% of 333.16MiB at 98.86KiB/s ETA 57:34ERROR: '<' not supported between instances of 'float' and 'str'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1389, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1473, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1529, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2638, in process_video_result
    self.process_info(new_info)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3110, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2835, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 453, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/http.py", line 384, in real_download
    return download()
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/http.py", line 334, in download
    if speed and speed < (self.params.get('throttledratelimit') or 0):
TypeError: '<' not supported between instances of 'float' and 'str'

**Comment by ssean** [comment]
This is a known bug in yt-dlp. Please close/delete. Thanks.

**Comment by BromTeque** [comment]
YT-DLP issue can be found [here](https://github.com/yt-dlp/yt-dlp/issues/2996)

Temporary fix: Revert to version 2022.03.08
