### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'Muse Asia - 20220409 - SPY▒FAMILY - Episode 01 [English Sub] [-Ivz-tSWRmY].mkv'

### ISSUE THREAD

**Issue by NomaanMalick** [TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection#89]
```[debug] Command-line config: ['--format', '(bestvideo[vcodec^=av01][height>=4320][fps>30]/bestvideo[vcodec^=vp9.2][height>=4320][fps>30]/bestvideo[vcodec^=vp9][height>=4320][fps>30]/bestvideo[vcodec^=avc1][height>=4320][fps>30]/bestvideo[height>=4320][fps>30]/bestvideo[vcodec^=av01][height>=4320]/bestvideo[vcodec^=vp9.2][height>=4320]/bestvideo[vcodec^=vp9][height>=4320]/bestvideo[vcodec^=avc1][height>=4320]/bestvideo[height>=4320]/bestvideo[vcodec^=av01][height>=2880][fps>30]/bestvideo[vcodec^=vp9.2][height>=2880][fps>30]/bestvideo[vcodec^=vp9][height>=2880][fps>30]/bestvideo[vcodec^=avc1][height>=2880][fps>30]/bestvideo[height>=2880][fps>30]/bestvideo[vcodec^=av01][height>=2880]/bestvideo[vcodec^=vp9.2][height>=2880]/bestvideo[vcodec^=vp9][height>=2880]/bestvideo[vcodec^=avc1][height>=2880]/bestvideo[height>=2880]/bestvideo[vcodec^=av01][height>=2160][fps>30]/bestvideo[vcodec^=vp9.2][height>=2160][fps>30]/bestvideo[vcodec^=vp9][height>=2160][fps>30]/bestvideo[vcodec^=avc1][height>=2160][fps>30]/bestvideo[height>=2160][fps>30]/bestvideo[vcodec^=av01][height>=2160]/bestvideo[vcodec^=vp9.2][height>=2160]/bestvideo[vcodec^=vp9][height>=2160]/bestvideo[vcodec^=avc1][height>=2160]/bestvideo[height>=2160]/bestvideo[vcodec^=av01][height>=1440][fps>30]/bestvideo[vcodec^=vp9.2][height>=1440][fps>30]/bestvideo[vcodec^=vp9][height>=1440][fps>30]/bestvideo[vcodec^=avc1][height>=1440][fps>30]/bestvideo[height>=1440][fps>30]/bestvideo[vcodec^=av01][height>=1440]/bestvideo[vcodec^=vp9.2][height>=1440]/bestvideo[vcodec^=vp9][height>=1440]/bestvideo[vcodec^=avc1][height>=1440]/bestvideo[height>=1440]/bestvideo[vcodec^=av01][height>=1080][fps>30]/bestvideo[vcodec^=vp9.2][height>=1080][fps>30]/bestvideo[vcodec^=vp9][height>=1080][fps>30]/bestvideo[vcodec^=avc1][height>=1080][fps>30]/bestvideo[height>=1080][fps>30]/bestvideo[vcodec^=av01][height>=1080]/bestvideo[vcodec^=vp9.2][height>=1080]/bestvideo[vcodec^=vp9][height>=1080]/bestvideo[vcodec^=avc1][height>=1080]/bestvideo[height>=1080]/bestvideo[vcodec^=av01][height>=720][fps>30]/bestvideo[vcodec^=vp9.2][height>=720][fps>30]/bestvideo[vcodec^=vp9][height>=720][fps>30]/bestvideo[vcodec^=avc1][height>=720][fps>30]/bestvideo[height>=720][fps>30]/bestvideo[vcodec^=av01][height>=720]/bestvideo[vcodec^=vp9.2][height>=720]/bestvideo[vcodec^=vp9][height>=720]/bestvideo[vcodec^=avc1][height>=720]/bestvideo[height>=720]/bestvideo[vcodec^=av01][height>=480][fps>30]/bestvideo[vcodec^=vp9.2][height>=480][fps>30]/bestvideo[vcodec^=vp9][height>=480][fps>30]/bestvideo[vcodec^=avc1][height>=480][fps>30]/bestvideo[height>=480][fps>30]/bestvideo[vcodec^=av01][height>=480]/bestvideo[vcodec^=vp9.2][height>=480]/bestvideo[vcodec^=vp9][height>=480]/bestvideo[vcodec^=avc1][height>=480]/bestvideo[height>=480]/bestvideo[vcodec^=av01][height>=360][fps>30]/bestvideo[vcodec^=vp9.2][height>=360][fps>30]/bestvideo[vcodec^=vp9][height>=360][fps>30]/bestvideo[vcodec^=avc1][height>=360][fps>30]/bestvideo[height>=360][fps>30]/bestvideo[vcodec^=av01][height>=360]/bestvideo[vcodec^=vp9.2][height>=360]/bestvideo[vcodec^=vp9][height>=360]/bestvideo[vcodec^=avc1][height>=360]/bestvideo[height>=360]/bestvideo[vcodec^=avc1][height>=240][fps>30]/bestvideo[vcodec^=av01][height>=240][fps>30]/bestvideo[vcodec^=vp9.2][height>=240][fps>30]/bestvideo[vcodec^=vp9][height>=240][fps>30]/bestvideo[height>=240][fps>30]/bestvideo[vcodec^=avc1][height>=240]/bestvideo[vcodec^=av01][height>=240]/bestvideo[vcodec^=vp9.2][height>=240]/bestvideo[vcodec^=vp9][height>=240]/bestvideo[height>=240]/bestvideo[vcodec^=avc1][height>=144][fps>30]/bestvideo[vcodec^=av01][height>=144][fps>30]/bestvideo[vcodec^=vp9.2][height>=144][fps>30]/bestvideo[vcodec^=vp9][height>=144][fps>30]/bestvideo[height>=144][fps>30]/bestvideo[vcodec^=avc1][height>=144]/bestvideo[vcodec^=av01][height>=144]/bestvideo[vcodec^=vp9.2][height>=144]/bestvideo[vcodec^=vp9][height>=144]/bestvideo[height>=144]/bestvideo)+(bestaudio[acodec^=opus]/bestaudio)/best', '--verbose', '--force-ipv4', '--ignore-errors', '--no-continue', '--no-overwrites', '--download-archive', 'archive.log', '--add-metadata', '--parse-metadata', '%(title)s:%(meta_title)s', '--parse-metadata', '%(uploader)s:%(meta_artist)s', '--all-subs', '--embed-subs', '--check-formats', '--concurrent-fragments', '5', '--output', '%(uploader)s - %(upload_date)s - %(title)s [%(id)s].%(ext)s', '--merge-output-format', 'mkv', '--throttled-rate', '100K', '--batch-file', 'Source - Watch on PC.txt']
[debug] Batch file urls: ['https://www.youtube.com/watch?v=-Ivz-tSWRmY']
[debug] Encodings: locale cp1252, fs utf-8, out cp1252 (No ANSI), err cp1252 (No ANSI), pref cp1252
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.9.12 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-04-07-git-607ecc27ed-full_build-www.gyan.dev (setts), ffprobe 2022-04-07-git-607ecc27ed-full_build-www.gyan.dev
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] Loading archive file 'archive.log'
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=-Ivz-tSWRmY
[youtube] -Ivz-tSWRmY: Downloading webpage
[youtube] -Ivz-tSWRmY: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Downloading subtitles: live_chat
[debug] Searching for '(?P<meta_title>.+)' in '%(title)s'
[MetadataParser] Parsed meta_title from '%(title)s': 'SPY▒FAMILY - Episode 01 [English Sub]'
[debug] Searching for '(?P<meta_artist>.+)' in '%(uploader)s'
[MetadataParser] Parsed meta_artist from '%(uploader)s': 'Muse Asia'
[info] Testing format 398
[debug] File locking is not supported on this platform. Proceeding without locking
[download] Destination: C:\Users\Nomaan\Downloads\TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection-3.2.2\TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection-3.2.2\scripts\Watch Scripts\Watch on PC Script\tmpq_pj4zgj.tmp
[download] 100% of 10.00KiB in 00:00
[info] Testing format 251
[download] Destination: C:\Users\Nomaan\Downloads\TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection-3.2.2\TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection-3.2.2\scripts\Watch Scripts\Watch on PC Script\tmp2fg0ewt5.tmp
[download] 100% of 10.00KiB in 00:00
[info] -Ivz-tSWRmY: Downloading 1 format(s): 398+251
[info] Writing video subtitles to: Muse Asia - 20220409 - SPY▒FAMILY - Episode 01 [English Sub] [-Ivz-tSWRmY].live_chat.json
[debug] Invoking downloader on "https://www.youtube.com/watch?v=-Ivz-tSWRmY"
[youtube_live_chat] Downloading live chat
[youtube_live_chat] Total fragments: unknown (live)
[download] Destination: Muse Asia - 20220409 - SPY▒FAMILY - Episode 01 [English Sub] [-Ivz-tSWRmY].live_chat.json
[download] 100% of 10.71MiB in 01:52
[debug] Invoking downloader on "https://rr2---sn-ci5gup-pmwe.googlevideo.com/videoplayback?expire=1650221128&ei=6AtcYqHNEfK9z7sPhvi2uAk&ip=171.50.187.106&id=o-AL6blf-eJe1YB99zDM_Rtqtp7Pye8N97g2hm9rWE9L_z&itag=398&source=youtube&requiressl=yes&mh=PY&mm=31%2C29&mn=sn-ci5gup-pmwe%2Csn-ci5gup-cvhk&ms=au%2Crdu&mv=m&mvi=2&pl=20&gcr=in&initcwndbps=922500&vprv=1&mime=video%2Fmp4&gir=yes&clen=81938701&dur=1449.906&lmt=1649528549700359&mt=1650199256&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAKm8OHJCQp5-pVPsydrNv082qHUwTuNro06K8RkZxSZHAiBKo3_wuKCwcW8KCZbSlCYwFFPIZ9WYHKmKL0LGH6LP0A%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgZquTQWdMKRaUL0DAYo01G1n40spSLRwh9rDPcA6vA7YCIB-hxBZIY0sh8K7dqxTuoMHYmaZ4WRzDtYZEaCMcUjgU"
[download] Destination: Muse Asia - 20220409 - SPY▒FAMILY - Episode 01 [English Sub] [-Ivz-tSWRmY].f398.mp4
[download] 100% of 78.14MiB in 00:18
[debug] Invoking downloader on "https://rr2---sn-ci5gup-pmwe.googlevideo.com/videoplayback?expire=1650221128&ei=6AtcYqHNEfK9z7sPhvi2uAk&ip=171.50.187.106&id=o-AL6blf-eJe1YB99zDM_Rtqtp7Pye8N97g2hm9rWE9L_z&itag=251&source=youtube&requiressl=yes&mh=PY&mm=31%2C29&mn=sn-ci5gup-pmwe%2Csn-ci5gup-cvhk&ms=au%2Crdu&mv=m&mvi=2&pl=20&gcr=in&initcwndbps=922500&vprv=1&mime=audio%2Fwebm&gir=yes&clen=22337593&dur=1449.921&lmt=1649527564043773&mt=1650199256&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAK02WjA320zvdY7KWC9QoXd4KgGX4fgSXRTZ4SJrE1SEAiEAtaKVqprVPHOAAMBADhbB61Fori-iz4lQ1e9cUWcuGI8%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgZquTQWdMKRaUL0DAYo01G1n40spSLRwh9rDPcA6vA7YCIB-hxBZIY0sh8K7dqxTuoMHYmaZ4WRzDtYZEaCMcUjgU"
[download] Destination: Muse Asia - 20220409 - SPY▒FAMILY - Episode 01 [English Sub] [-Ivz-tSWRmY].f251.webm
[download] 100% of 21.30MiB in 00:03
[Merger] Merging formats into "Muse Asia - 20220409 - SPY▒FAMILY - Episode 01 [English Sub] [-Ivz-tSWRmY].mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Muse Asia - 20220409 - SPY▒FAMILY - Episode 01 [English Sub] [-Ivz-tSWRmY].f398.mp4" -i "file:Muse Asia - 20220409 - SPY▒FAMILY - Episode 01 [English Sub] [-Ivz-tSWRmY].f251.webm" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" "file:Muse Asia - 20220409 - SPY▒FAMILY - Episode 01 [English Sub] [-Ivz-tSWRmY].temp.mkv"
[debug] ffmpeg version 2022-04-07-git-607ecc27ed-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11.2.0 (Rev7, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      57. 24.101 / 57. 24.101
  libavcodec     59. 25.101 / 59. 25.101
  libavformat    59. 20.101 / 59. 20.101
  libavdevice    59.  6.100 / 59.  6.100
  libavfilter     8. 30.100 /  8. 30.100
  libswscale      6.  6.100 /  6.  6.100
  libswresample   4.  6.100 /  4.  6.100
  libpostproc    56.  5.100 / 56.  5.100
file:Muse Asia - 20220409 - SPY▒FAMILY - Episode 01 [English Sub] [-Ivz-tSWRmY].f398.mp4: No such file or directory
ERROR: file:Muse Asia - 20220409 - SPY▒FAMILY - Episode 01 [English Sub] [-Ivz-tSWRmY].f398.mp4: No such file or directory
Traceback (most recent call last):
  File "C:\Users\Nomaan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\yt_dlp\YoutubeDL.py", line 3339, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "C:\Users\Nomaan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\yt_dlp\postprocessor\common.py", line 27, in run
    ret = func(self, info, *args, **kwargs)
  File "C:\Users\Nomaan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\yt_dlp\postprocessor\common.py", line 124, in wrapper
    return func(self, info)
  File "C:\Users\Nomaan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\yt_dlp\postprocessor\ffmpeg.py", line 828, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "C:\Users\Nomaan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\yt_dlp\postprocessor\ffmpeg.py", line 288, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
  File "C:\Users\Nomaan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\yt_dlp\postprocessor\ffmpeg.py", line 327, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.split('\n')[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: file:Muse Asia - 20220409 - SPY▒FAMILY - Episode 01 [English Sub] [-Ivz-tSWRmY].f398.mp4: No such file or directory

WARNING: JSON subtitles cannot be embedded
[Metadata] Adding metadata to "Muse Asia - 20220409 - SPY▒FAMILY - Episode 01 [English Sub] [-Ivz-tSWRmY].mkv"
ERROR: [WinError 2] The system cannot find the file specified: 'Muse Asia - 20220409 - SPY▒FAMILY - Episode 01 [English Sub] [-Ivz-tSWRmY].mkv'
Traceback (most recent call last):
  File "C:\Users\Nomaan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\yt_dlp\YoutubeDL.py", line 1408, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Nomaan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\yt_dlp\YoutubeDL.py", line 1492, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\Nomaan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\yt_dlp\YoutubeDL.py", line 1548, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "C:\Users\Nomaan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\yt_dlp\YoutubeDL.py", line 2648, in process_video_result
    self.process_info(new_info)
  File "C:\Users\Nomaan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\yt_dlp\YoutubeDL.py", line 3211, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "C:\Users\Nomaan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\yt_dlp\YoutubeDL.py", line 3379, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "C:\Users\Nomaan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\yt_dlp\YoutubeDL.py", line 3366, in run_all_pps
    info = self.run_pp(pp, info)
  File "C:\Users\Nomaan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\yt_dlp\YoutubeDL.py", line 3339, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "C:\Users\Nomaan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\yt_dlp\postprocessor\common.py", line 27, in run
    ret = func(self, info, *args, **kwargs)
  File "C:\Users\Nomaan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\yt_dlp\postprocessor\common.py", line 124, in wrapper
    return func(self, info)
  File "C:\Users\Nomaan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\yt_dlp\postprocessor\ffmpeg.py", line 706, in run
    self.run_ffmpeg_multiple_files(
  File "C:\Users\Nomaan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\yt_dlp\postprocessor\ffmpeg.py", line 288, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
  File "C:\Users\Nomaan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\yt_dlp\postprocessor\ffmpeg.py", line 295, in real_run_ffmpeg
    oldest_mtime = min(
  File "C:\Users\Nomaan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\yt_dlp\postprocessor\ffmpeg.py", line 296, in <genexpr>
    os.stat(encodeFilename(path)).st_mtime for path, _ in input_path_opts if path)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'Muse Asia - 20220409 - SPY▒FAMILY - Episode 01 [English Sub] [-Ivz-tSWRmY].mkv'```

**Comment by BromTeque** [comment]
video unavailable

**Comment by BromTeque** [comment]
Cannot reproduce. Please switch to {the ffmpeg build provided by YT-DLP](https://github.com/yt-dlp/FFmpeg-Builds) and try again.

**Comment by NomaanMalick** [comment]
> Cannot reproduce. Please switch to [the ffmpeg build provided by YT-DLP](https://github.com/yt-dlp/FFmpeg-Builds/releases) and try again.

Which among the ones listed there should I get?

**Comment by BromTeque** [comment]
@NomaanMalick 

My bad. I was gonna link the the readme where there is an download button, but I switched to releases last minute.

Here's a direct link (It looks like you're on Windows):

https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip

**Comment by NomaanMalick** [comment]
> @NomaanMalick
> 
> My bad. I was gonna link the the readme where there is an download button, but I switched to releases last minute.
> 
> Here's a direct link (It looks like you're on Windows):
> 
> https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip

Thank you for linking to the release I should get. However, I still get the same error even after replacing ffmpeg.

**Comment by TheFrenchGhosty** [comment]
How are you running the scripts?

**Comment by TheFrenchGhosty** [comment]
Path length issue, Cygwin doesn't bypass it.

Either shorten your path (might not fix it consistently), or use WSL.

**Comment by NomaanMalick** [comment]
> Path length issue, Cygwin doesn't bypass the 255 characters limit.
> 
> Either shorten your path (might not fix it consistently), or use WSL.

It used to work earlier. I think the issue started with the new update.

**Comment by TheFrenchGhosty** [comment]
>It used to work earlier. I think the issue started with the new update.

No, it can't work if you hit the path length, if it worked before it means you weren't hitting it.

**Comment by NomaanMalick** [comment]
> > It used to work earlier. I think the issue started with the new update.
> 
> No, it can't work if you hit the path length, if it worked before it means you weren't hitting it.

That's strange. I could swear that I used to have no problems with files with longer titles. Still, I will do as you say and make the path length shorter. Thank you!
